### ISSUE TITLE
Add TLA+ grammar extension

### ISSUE THREAD

**Issue by pmer** [TeamTilapia/vscode-tilapia#1]
### Grammar (syntax highlighting)

[Grammars](https://code.visualstudio.com/docs/extensions/themes-snippets-colorizers) have two parts:

- A configuration file "./language-configuration.json" in our extension. It teaches VS Code what TLA+ comments and string are. (Wait, does TLA+ have strings?)

- A TextMate grammar for the language. Maybe [agentultra/TLAGrammar](https://github.com/agentultra/TLAGrammar)? Looks like the [same highlighter that GitHub uses](https://github.com/github/linguist/pull/2990) when coloring TLA+ files. It lacks support for highlighting PlusCal expressions inside comments.

Also, just for fun, check [this](https://github.com/github/linguist/issues/2693#issuecomment-245679325) out for a read about the complexity of TLA+ grammars. It's a reminder that TLA+ expressions are even more whitespace-dependent for semantics than Python.

**Comment by danielmai** [comment]
The grammar for TLA+ is defined in page 276 (PDF page 294) of [Specifying Systems](http://lamport.azurewebsites.net/tla/book-02-08-08.pdf).

The formal grammar of PlusCal is defined in page 57 (PDF page 60) of [A PlusCal User’s Manual
C-Syntax∗ Version 1.8](http://lamport.azurewebsites.net/tla/c-manual.pdf).

Documentation on TextMate language grammar specification is at https://manual.macromates.com/en/language_grammars.

**Comment by danielmai** [comment]
The TLA+/C-style PlusCal/P-style PlusCal grammars that are used in the Toolbox is described in [TokenizeSpec.java](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tla2tex/TokenizeSpec.java). Maybe this can tell us how to implement the VS Code grammar correctly for colorizing.

**Comment by pmer** [comment]
We're running into trouble making PlusCal programs looks different from TLA+ comments.

Let's try coloring everything in PlusCal programs.

Goal: Having it look like the TLA+ Toolbox and not be a completely separate color.
